version: '3'
services:
  app:
    container_name: image-management-recipe-delice
    build: .
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - '3001:3000'
    depends_on:
      - db
  db:
    image: mysql:latest
    container_name: gestion_recette_delice
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - '3308:3306'
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
