services:
  api:
    build: .
    ports:
      - '3090:3090'
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    volumes:
      # - db-data:/var/lib/mysql
      - .:/usr/app
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - '3308:3306'
    volumes:
      # - .:/usr/app
      - db-data:/var/lib/mysql
volumes:
  db-data:
